fail_fast: true

repos:
  - repo: local
    hooks:
      # Keep schema always up to date
      - id: schema
        name: Generate jsonschema
        entry: cargo test
        pass_filenames: false
        language: system
        types: [rust]
