fail_fast: true

repos:
  - repo: local
    hooks:
      # Force code to be (somewhat) clea
      - id: lint
        name: Lint qmk_build
        entry: cargo clippy -- -Wclippy::pedantic -Dwarnings
        pass_filenames: false
        language: system
        types: [rust]

      # Generate the binary and add it to $PATH
      - id: build
        name: Compile and install qmk_build
        entry: cargo install --path .
        pass_filenames: false
        language: system
        types: [rust]

      # Keep schema always up to date
      - id: schema
        name: Generate jsonschema
        entry: cargo test
        pass_filenames: false
        language: system
        types: [rust]
